version: 0.0
os: linux
files:
  - source: webapp-sample/
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    wip\/.*: ~ 
    main:
        deploymentGroupName: DemoDeploymentGroup
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::471112798057:role/CodeDeployRole