name : Push code to EC2 imaage
on:
  push:
    branches: main 

permissions:
      id-token: write
      contents: write 

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: AWS_Environment
    steps:
      - name : Checkout Code
        uses: actions/checkout@v4
      - name : List directory
        run : ls -al 
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token : ${{ secrets.AWS_SESSION_TOKEN }}
      - name : Create Code Deploy
        id: deploy
        uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
        with:
              application: DemoApplication
      - name : Print Commit Message
        uses: peter-evans/commit-comment@v2
        with:
              application: DemoApplication
              token: ${{ secrets.CODEDEPLOY_TOKEN }}
              body: |
                    @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=us-east-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.

            
